### ISSUE TITLE
Incorrect work of cache

### ISSUE THREAD

**Issue by SergeyBogdanov** [oleg-shilo/cs-script#86] opened 2017-09-15 10:52 UTC
Hi,
I have encountered a problem with caching in cscs.exe (CS-Script 3.27.5):

Here is the content of Test.cs for the problem demonstration:
```
using System;
using Microsoft.Build.Framework;
public class Program
{
    static public void Main(string[] args)
    {
        Console.WriteLine(typeof(IBuildEngine).Assembly.Location);
    }
}
```

Here are the results of running Test.cs:
```
C:\>cscs /nl Test.cs
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll

C:\>cscs /nl -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin" Test.cs
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll

C:\>cscs -c:0 /nl -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin" Test.cs
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll
```

As you can see the GAC version of Microsoft.Build.Framework was loaded at first run.

At the second run you can see that despite the fact that -dir with VS2017 path was set, the GAC version of Microsoft.Build.Framework was loaded again. It's so because Test.cs was not recompiled and was loaded from cache.

And only after setting -c:0 Test.cs was recompiled and the proper version of Microsoft.Build.Framework was loaded.

**Comment by oleg-shilo** [comment] 2017-09-15 13:09
Interesting. Assembly probing can be tricky. Caching should not affect it. The assembly is picked from the first successful directory in the "probing dirs" list. This list may be vary depending on the environment conditions (e.g. N++ host vs. command prompt).  But in your case I expect it to be the same.

Strangely enough your very test in my environment does not exhibit the problem: 
```ps
Q:\>cscs -c:1 -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin" "New
Script64.cs"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll

Q:\>cscs -c:0 -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin" "New
Script64.cs"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll

Q:\>cscs -c:0 "New Script64.cs"
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll

Q:\>cscs -c:1 "New Script64.cs"
C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll
```
Try to execute with `-verbose` switch. It may give you some clue.

In cases of complete assembly probing failure you can disable namespace resolution and specify the assembly explicitly from code:
```C#
//css_ignore_namespace Microsoft.Build.Framework
//css_ref C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll
```

**Comment by SergeyBogdanov** [comment] 2017-09-15 14:36
_Strangely enough your very test in my environment does not exhibit the problem_
Note that the problem is confirmed only if you firstly run cscs.exe without -dir and then with -dir key.
So to confirm you should run in the such way:
```
Q:\>cscs "New Script64.cs"
Q:\>cscs -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin" "NewScript64.cs"
```
I cleaned up the cache and run the following commands with -verbose:
```
(1) cscs -verbose /nl Test.cs
(2) cscs -verbose /nl Test.cs
(3) cscs /nl -verbose -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin" Test.cs
(4) cscs /nl -verbose -c:0 -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin" Test.cs
(5) cscs /nl -verbose -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin" Test.cs
```
The output is the following (you can see that (4) works properly but (3) and (5) do not and the only difference between them is that (4) does not use cache but (3) and (5) use cache created by (1)):
```
C:\>cscs -verbose /nl Test.cs
> ----------------
  TragetFramework: v4.0
  Provider:
  Engine: C:\cs-script\cscs.exe
  Console Encoding: cp866 (Cyrillic (DOS)) - system default
  CurrentDirectory: C:\
  NuGet manager: C:\cs-script\lib\nuget.exe
  NuGet cache: C:\ProgramData\CS-Script\nuget
  Executing: C:\Test.cs
  Script arguments:
  SearchDirectories:
    0 - C:\
    1 - C:\cs-script\lib
    2 - C:\ProgramData\CS-Script\inc
    3 - C:\cs-script
    4 - C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163
> ----------------

Compiling script...

  Precompilers:
   0 - Test.cs -> csscript.DefaultPrecompiler
           from C:\cs-script\cscs.exe

  Output file:
       C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163\Test.cs.compiled

  Files to compile:
   0 - C:\Test.cs
   1 - C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163\Test.attr.g.cs
   2 - C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\dbg.inject.-1383697267.cs

  References:
   0 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
   1 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Linq\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Linq.dll
   2 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
   3 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll
> ----------------
  Compiler Output:
> ----------------
Initialization time: 161,11 msec
Compilation time:    183,487 msec
> ----------------

C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll

C:\>cscs -verbose /nl Test.cs
> ----------------
  TragetFramework: v4.0
  Provider:
  Engine: C:\cs-script\cscs.exe
  Console Encoding: cp866 (Cyrillic (DOS)) - system default
  CurrentDirectory: C:\
  NuGet manager: C:\cs-script\lib\nuget.exe
  NuGet cache: C:\ProgramData\CS-Script\nuget
  Executing: C:\Test.cs
  Script arguments:
  SearchDirectories:
    0 - C:\
    1 - C:\cs-script\lib
    2 - C:\ProgramData\CS-Script\inc
    3 - C:\cs-script
    4 - C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163
> ----------------

  Loading script from cache...

  Cache file:
       C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163\Test.cs.compiled
> ----------------
Initialization time: 151,6537 msec
> ----------------
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll

C:\>cscs /nl -verbose -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin" Test.cs
> ----------------
  TragetFramework: v4.0
  Provider:
  Engine: C:\cs-script\cscs.exe
  Console Encoding: cp866 (Cyrillic (DOS)) - system default
  CurrentDirectory: C:\
  NuGet manager: C:\cs-script\lib\nuget.exe
  NuGet cache: C:\ProgramData\CS-Script\nuget
  Executing: C:\Test.cs
  Script arguments:
  SearchDirectories:
    0 - C:\
    1 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin
    2 - C:\cs-script\lib
    3 - C:\ProgramData\CS-Script\inc
    4 - C:\cs-script
    5 - C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163
> ----------------

  Loading script from cache...

  Cache file:
       C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163\Test.cs.compiled
> ----------------
Initialization time: 180,1394 msec
> ----------------
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll

C:\>cscs /nl -verbose -c:0 -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin" Test.cs
> ----------------
  TragetFramework: v4.0
  Provider:
  Engine: C:\cs-script\cscs.exe
  Console Encoding: cp866 (Cyrillic (DOS)) - system default
  CurrentDirectory: C:\
  NuGet manager: C:\cs-script\lib\nuget.exe
  NuGet cache: C:\ProgramData\CS-Script\nuget
  Executing: C:\Test.cs
  Script arguments:
  SearchDirectories:
    0 - C:\
    1 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin
    2 - C:\cs-script\lib
    3 - C:\ProgramData\CS-Script\inc
    4 - C:\cs-script
    5 - C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163
> ----------------

Compiling script...

  Precompilers:
   0 - Test.cs -> csscript.DefaultPrecompiler
           from C:\cs-script\cscs.exe

  Output file:
       C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\5156.c879eb0d-4591-4535-b1a2-b6e954d5dad0.dll

  Files to compile:
   0 - C:\Test.cs
   1 - C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163\Test.attr.g.cs
   2 - C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\dbg.inject.-1383697267.cs

  References:
   0 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
   1 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Linq\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Linq.dll
   2 - C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
   3 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll
> ----------------
  Compiler Output:
> ----------------
Initialization time: 150,133 msec
Compilation time:    159,9723 msec
> ----------------

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Build.Framework.dll

C:\>cscs /nl -verbose -dir:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin" Test.cs
> ----------------
  TragetFramework: v4.0
  Provider:
  Engine: C:\cs-script\cscs.exe
  Console Encoding: cp866 (Cyrillic (DOS)) - system default
  CurrentDirectory: C:\
  NuGet manager: C:\cs-script\lib\nuget.exe
  NuGet cache: C:\ProgramData\CS-Script\nuget
  Executing: C:\Test.cs
  Script arguments:
  SearchDirectories:
    0 - C:\
    1 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin
    2 - C:\cs-script\lib
    3 - C:\ProgramData\CS-Script\inc
    4 - C:\cs-script
    5 - C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163
> ----------------

  Loading script from cache...

  Cache file:
       C:\Users\sbogdano\AppData\Local\Temp\CSSCRIPT\Cache\769641163\Test.cs.compiled
> ----------------
Initialization time: 165,9609 msec
> ----------------
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll
```

**Comment by oleg-shilo** [comment] 2017-09-16 10:18
Yep, I got is now. Will work on it. 
Please try that fix with explicit dll referencing that I suggested in my post. Let me know if it addressed the issue for a mean time.

**Comment by oleg-shilo** [comment] 2017-09-17 11:32
The problem is caused by the fact that adding a probing directory (from CLI) does not invalidates existing cache. 

While this approach seems to be reasonably adequate it clearly failing in the cases like yours.  

The fix is committed and it will be available in the next release. In a mean time please use the work around I suggested as it should work in your case.

**Comment by SergeyBogdanov** [comment] 2017-09-17 19:13
_>>The fix is committed and it will be available in the next release. In a mean time please use the work around I suggested as it should work in your case._
Great! Thank you! Currently I'm using a workaround similar to the offered by you: I've just specified something like `//css_searchdir %ProgramFiles(x86)%\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer`, so `//css_ignore_namespace` is not required.

**Closed** 2018-03-14 23:54 UTC
Labels: defect, question
