### ISSUE TITLE
Hosted Script Execution cannot resolve Nuget Package

### ISSUE THREAD

**Issue by Meigyoku-Thmn** [oleg-shilo/cs-script#167] opened 2019-06-29 16:57 UTC
I used `//css_nuget Cyotek.Windows.Forms.FontDialog` in my script then run it using:
```cs
var script = new AsmHelper(CSScript.LoadFile(mainScriptPath, null, true));
script.GetStaticMethod("Config.OnInit")();
```
I just get this exception:
```
System.IO.FileNotFoundException: Could not load file or assembly 'Cyotek.Windows.Forms.FontDialog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=58daa28b0b2de221' or one of its dependencies. The system cannot find the file specified.

File name: 'Cyotek.Windows.Forms.FontDialog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=58daa28b0b2de221'
```
I also used Assembly.GetExecutingAssembly().GetReferencedAssemblies() inside my script and `Cyotek.Windows.Forms.FontDialog` is listed as a dependency, so the build process works properly and the package is downloaded to `C:\ProgramData\CS-Script\nuget`. So the problem is occurs in run process, it seems that CS-Script never resolves any nuget package in Hosted Script Execution.

Do I really have to write resolver by myself to resolve every referenced nuget packages case by case?

**Comment by oleg-shilo** [comment] 2019-06-30 12:22
The problem is rather logical than technical.

You are loading the assembly to the host process. The host (your application) cannot possibly know where the all dependencies of that assembly are located. And yet resolving dependencies is always the responsibility of the host. 

In your case you use CS-Script to compile/load the script and you use your application runtime to load/execute it. Meaning that you will need to handle assembly probing for the directories where dependencies (e.g. NuGet packages) are. You can do this by "asking" CS-Script runtime for packages location and `SimpleAsmProbing` for setting up the probing algorithm:

```C#
var script_file = @"C:\Users\user\Documents\C# Scripts\New Script11.cs";

var package_dirs = new ScriptParser(script_file).ResolvePackages()
                                                .Select(Path.GetDirectoryName)
                                                .ToArray();

using (SimpleAsmProbing.For(package_dirs))
{
    // use dynamic
    // dynamic scipt_obj = CSScript.LoadFile(script_file).CreateObject("Script");
    // scipt_obj.main();

    // or use static
    var script_asm = new AsmHelper(CSScript.LoadFile(script_file, null, true));
    script_asm.GetStaticMethod("Script.Main")();
}
```
And if you prefer generic global probing then you can use something like that:
```C#
var script_file = @"C:\Users\user\Documents\C# Scripts\New Script11.cs";

var package_dirs = new ScriptParser(script_file).ResolvePackages()
                                                .Select(Path.GetDirectoryName)
                                                .ToList();

package_dirs.ForEach(dir => CSScript.GlobalSettings.AddSearchDir(dir));

var script_asm = new AsmHelper(CSScript.LoadFile(script_file, null, true));
script_asm.GetStaticMethod("Script.Main")();
```

**Comment by Meigyoku-Thmn** [comment] 2019-07-01 02:20
Thanks! Didn't know about the ScriptParser.

**Comment by oleg-shilo** [comment] 2019-07-01 08:20
Yeah, your scenario is a bit unusual. Typically host app references all NuGet packages and the scripts are clean without raw nuget references but reference all assemblies from the host app directory.

Saying that, there is nothing wrong with your scenario. It's just less common. That's it :)

**Comment by hanabi1224** [comment] 2019-07-24 14:47
@oleg-shilo What's the equivalent of ScriptParser in script-cs.core nuget?

**Comment by oleg-shilo** [comment] 2019-07-25 11:46
Currently there is none. I had to implement ScriptParser in .NET Full because Roslyn parser is not easily available there and ScriptParser was a simple answer to the need to aggregate included/imported scripts as well as nuget packages.

In .NETCore Roslyn parser is always available. Including/importing scripts is impossible dues to the .NETCore limitations (only hosted execution is affected). Referencing NuGet packages in the hosted scenario is also no go. Thus there is no need/benefit in using ScriptParser when hosting the engine and all `//css_*` parsing is addressed with `CSScriptLib.CSharpParser`.

Though if you have a valid use case I will consider including `ScriptParser` in the package. What is your use-case? Can you give me more details?

**Comment by hanabi1224** [comment] 2019-07-27 05:43
@oleg-shilo The scenario is like, to build a aws lambda runtime, that picks up a cs-script to as lambda handler dynamically.  The lambda runtime will only have minimal nuget preinstalled so that it will need the script to be able to install packages at runtime.  Does that make sense?

**Comment by oleg-shilo** [comment] 2019-07-28 12:15
> Does that make sense?

Yes and No :)

It makes perfect sense functionality wise but I am not fully convinced it is a responsibility of the script engine to download the nuget packages. Finding them... may be. But pulling them from NuGet server is a typical task of the host application. 

Thus you can pack your host app with NuGet executable and pull the required packages at runtime. And then simply references the package assemblies in your scripts. 

Locating the assemblies should be a trivial task as you know what packages are and where they are downloaded. Would this address your problem?

**Comment by hanabi1224** [comment] 2019-07-28 14:08
@oleg-shilo I'm 100% with you on the point that it's not script engine's responsibility to download nuget packages, however, as a library, it should provide api for caller (host) to be able to achieve the tasks easily instead of implementing the nuget installer by themselves.

**Comment by hanabi1224** [comment] 2019-07-28 14:29
Also IMHO, cs-script has 3 main use cases.
1. As a standalone script runner (which cscs.exe has done)
2. Provide API for hosted environment
3. Compile cs scripts as dlls(with necessary dependencies) for host to pickup (which saves compile time cost, e.g. aws lambda has memory limitation to compile dynamically but it can still pickup compiled scripts in format of dll)

For bullet 3, I believe it does need the capability of resolving nuget dependencies.
For bullet 2, I'm not sure how cs-script is currently implemented but if it compiles and loads scripts into a separate app domain (which may not share be base directory with host), then I needs to be capable of resolving nuget dependencies as well.

**Comment by oleg-shilo** [comment] 2019-07-30 12:01
> @oleg-shilo I'm 100% with you on the point that it's not script engine's responsibility to download nuget packages, however, as a library, it should provide api for caller (host) to be able to achieve the tasks easily instead of implementing the nuget installer by themselves.

I am afraid we are not entirely on the same page here :)

No scripting languages provide API for driving package management mechanism. If they did then they would need to include the entire scripting platform infrastructure in your host app. It's unlikely that users would be happy with that. 

Let's take Python. It can import already installed package but it does not provide any runtime API for for `pip` to drive it from your host app. Instead your host will execute `pip` shell command. The same for TypeScript, Ruby, etc.

**Closed** 2019-10-14 14:02 UTC
Labels: question
