### ISSUE TITLE
compilation hangs!

### ISSUE THREAD

**Issue by eugene-vv** [oleg-shilo/cs-script#300] opened 2022-06-23 06:45 UTC
Hi Oleg,
We met another issue which easy to reproduce but leads to hangs of execution. When we run "cscs.exe somescript.cs" command line and somescript.cs has several errors the process hangs. Looks like problem in analysis of stdout/stderr buffers of child dotnet process. The cscs read them after execution completed but size of buffers by default is small and if dotnet write there a lot information (compilation errors) the buffers become full and wait until they will be read.

**Comment by oleg-shilo** [comment] 2022-06-23 14:12
Interestingly enough the script engine does not allocate any buffer but simply reads the output stream as a whole (line 66):
![image](https://user-images.githubusercontent.com/16729806/175319542-488643aa-16c9-4298-89ff-361675344460.png)

As you can see from the comments there .NET 6 has introduced some new behaviour compared to .NET Framework when it comes to STDOUT and STDERR redirection.

 I will see if I can reproduce it. 
 When you say "there a lot information", how much information is it?

**Comment by oleg-shilo** [comment] 2022-06-26 00:59
Hm..., I cannot reproduce it.

```txt
PS D:\dev\support\cs-script-#300> cscs --version
4.4.7.0
PS D:\dev\support\cs-script-#300> cscs -ng:csc .\no_ref.cs
Error: Specified file could not be compiled.

D:\dev\Galos\support\cs-script-#300\no_ref.cs(11,4): error CS0103:  The name 'a' does not exist in the current context
D:\dev\Galos\support\cs-script-#300\no_ref.cs(12,4): error CS0103:  The name 'b' does not exist in the current context
D:\dev\Galos\support\cs-script-#300\no_ref.cs(13,4): error CS0103:  The name 'c' does not exist in the current context
D:\dev\Galos\support\cs-script-#300\no_ref.cs(14,4): error CS0103:  The name 'd' does not exist in the current context
D:\dev\Galos\support\cs-script-#300\no_ref.cs(15,4): error CS0103:  The name 'e' does not exist in the current context
D:\dev\Galos\support\cs-script-#300\no_ref.cs(16,4): error CS0103:  The name 'f' does not exist in the current context
D:\dev\Galos\support\cs-script-#300\no_ref.cs(17,4): error CS0103:  The name 'g' does not exist in the current context
D:\dev\Galos\support\cs-script-#300\no_ref.cs(18,4): error CS0103:  The name 'h' does not exist in the current context
D:\dev\Galos\support\cs-script-#300\no_ref.cs(19,4): error CS0103:  The name 'k' does not exist in the current context
D:\dev\Galos\support\cs-script-#300\no_ref.cs(20,4): error CS0103:  The name 'l' does not exist in the current context
```
The csc I am using is .NET6 version
```txt
PS D:\dev\Galos\support\cs-script-#300> cscs
C# Script execution engine (.NET Core). Version 4.4.7.0.
   . . .
   Compiler engine: csc (C:\Program Files\dotnet\sdk\6.0.301\Roslyn\bincore\csc.dll)
                  : dotnet (C:\Program Files\dotnet\dotnet.exe)
   . . .
```

While the problem might be triggered by the rest of your environment I am still concerned about csc.exe not returning in your case.

You can try to execute csc.exe directly with the same parameters and see if it exits. If it does then you check (in the hello-world project) if `Process.StandardOutput.ReadToEnd()` exits.

**Comment by oleg-shilo** [comment] 2022-06-28 12:44
Agree.

It might be related to the v4.4.7 change:

>CLI
    Fixed the problem with possible double referencing GAC assemblies for CSC engine due to the nuget dependencies on GAC assemblies of the different versions.

If csc was choking on too many assemblies being referenced. Still, it should not chock but exit. Even with the error exit code.
But.... if it works as expected now, then let's just take it as is.

**Comment by oleg-shilo** [comment] 2022-06-28 12:52
Closing unless it reappears

**Closed as completed by oleg-shilo** 2022-06-28 12:52 UTC
Labels: question
