### ISSUE TITLE
Mono.CSharp.InternalErrorException in a simple script

### ISSUE THREAD

**Issue by rstarkov** [oleg-shilo/cs-script#38] opened 2017-01-22 15:15 UTC
1. Create a new Console project
2. Install CS-Script.bin NuGet package (3.19.0)
3. Paste this code to reproduce the exception:

        using CSScriptLibrary;

        public interface ITest
        {
            void Main(string[] args);
        }

        class Program
        {
            static void Main(string[] args)
            {
                CSScript.Evaluator.LoadCode<ITest>(@"
                    public class FooScript : ITest
                    {
                        public void Main(string[] args)
                        {
                            return;

                            bool foo = true;
                            switch (args[0])
                            {
                                case ""blah"":
                                    foo = false;
                                    break;
                                }

                                System.Console.WriteLine(foo);
                        }
                    }
                ");
            }
        }

This results in a `Mono.CSharp.InternalErrorException`.

The program is a little weird, admittedly. Removing any part of it makes the exception go away. The original code made more sense; I'm debugging a script and inserting a "return" halfway through some code. The fact that I can't execute that is a problem.

**Comment by oleg-shilo** [comment] 2017-01-23 00:42
It is a Mono bug that is fixed in the latest Mono.CSharp.dll. 

The problem is being addressed and the CS-Script distros are already patched (but not released yet) with the latest Mono dll, thanks issue #27 

I have tested your code and it works with the both other CS-Script engines - CodeDom and Roslyn. And the manual substitution of Mono.CSharp.dll also fixes the issue. 

The next release is scheduled for this week. In a mean time you can use CodeDom (also lets you to debug) or Roslyn evaluator: 

```C#
CSScript.RoslynEvaluator.LoadCode<ITest>(...
CSScript.CodeDomEvaluator.LoadCode<ITest>(...
//or 
CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
CSScript.Evaluator.LoadCode<ITest>(...
```

**Closed** 2017-02-14 02:36 UTC
Labels: duplicate, question
