### ISSUE TITLE
cs-script 4.8.5 doesn't show information about server on Linux

### ISSUE THREAD

**Issue by shitpoet** [oleg-shilo/cs-script#346] opened 2023-10-18 17:20 UTC
cs-script 4.8.5 installed on Debian 12 Linux as 

```
dotnet tool install --global cs-script.cli
```

doesn't show information about server:

```
~/tmp/cs$ css -server
Build server is not deployed.
Expected deployment: /usr/local/share/cs-script/bin/compiler/4.8.5.0/build.dll
Could not find file "-server".
Ensure it is in one of the CS-Script search/probing directories.
```

```
~/tmp/cs$ css -server:start
Could not find file "-server:start".
Ensure it is in one of the CS-Script search/probing directories.
~/tmp/cs$
```
It should show it according to the `-help` screen if I understand it correctly:
```
-server[:<start|stop|restart|add|remove|ping>]
    Prints the information about build server.
    Note, the server starts automatically on the script execution that is configured to use the 'csc'
    or 'roslyn' engine.
```

Config is default:
```
~/tmp/cs$ css -config
 UseAlternativeCompiler: ""
 ResolveRelativeFromParentScriptLocation: False
 DefaultArguments: "-c -ac:0"
 InjectScriptAssemblyAttribute: False
 EnableDbgPrint: True
 ResolveAutogenFilesRefs: True
 LegacyNugetSupport: True
 OpenEndDirectiveSyntax: True
 ConsoleEncoding: "default"
 LegacyTimestampCaching: False
 CustomTempDirectory: ""
 DefaultCompilerEngine: "csc"
 DefaultRefAssemblies: "System; System.Core;"
 SearchDirs: "%CSSCRIPT_ROOT%/lib;;%CSSCRIPT_INC%;"
 Precompiler: ""
 CustomHashing: True
 ReportDetailedErrorInfo: False
 HideCompilerWarnings: False
 InMemoryAssembly: True
 ConcurrencyControl: Standard
 ```
 No env variables are set for cs-script:
 ```
~/tmp/cs$ env | grep CSSCRIPT
~/tmp/cs$
```

**Comment by oleg-shilo** [comment] 2023-10-19 12:37
I am investigating it.
It's most likely caused by the differences in installation of cs-script as debian package comparing to dotnet tool.

Will let you know the outcome

**Comment by oleg-shilo** [comment] 2023-10-22 08:11
OK, it's an interesting one. It's not as bad as it looks like.

When you see this output:
```txt
Could not find file "<your command>".
Ensure it is in one of the CS-Script search/probing directories.
```
It is unconditionally printed at any server command regardless if it was successful or not. It was a mistake in the code and it is corrected now.

> I tried also css -server:add, but it does nothing:
   ```
   ~/tmp/cs$ css -server:add
   Access to the path '/usr/local/share/cs-script' is denied.
   Could not find file "-server:add".
   Ensure it is in one of the CS-Script search/probing directories.
   ~/tmp/cs$
   ```
A few problems here: 
- `Could not find file ` -  I just described it above
- `Access to the path` - this is because you need to have root access to execute this command. You need to run it with `sudo`.
  To make it more intuitive it prints the suggestion now:
   ![image](https://github.com/oleg-shilo/cs-script/assets/16729806/8b41a860-922f-42fe-88ec-d1f59c5e3c4b)

> then execution of css -server:add gives some unrelated message
   ```
    ~/tmp/cs$ css -server:add
    Could not find file "-server:add".
    Ensure it is in one of the CS-Script search/probing directories.
    ~/tmp/cs$
   ```
   - `Could not find file ` -  still the same
   -  But it actually deployed the build server. Just did not tell you about it. Now it does:
      ![image](https://github.com/oleg-shilo/cs-script/assets/16729806/73b4ef74-24ad-4ce2-a236-4e668b21a13c)
 
>  But maybe the idea was to create these folders during installation and dotnet tool install --global didn't do it?

Unfortunately, it's `dotnet tool install` does not allow you to have any behaviour. You cannot define any routine to create a folder and set its permissions. Thus it behaves as intended except not reapply communicating well to the user. This is fixed now and will be available in the very next release in a day or so.

**Comment by oleg-shilo** [comment] 2023-10-22 13:48
Done
You can update your deployment with v4.8.6.0

**Closed** 2023-11-08 14:42 UTC
Labels: done, Done: waiting for release

**Comment by oleg-shilo** [comment] 2023-11-11 22:44
Great trick. Txs. Did not know that.
